defradb:
  url: "http://localhost:9181"
  keyring_secret: "pingpong"
  p2p:
    enabled: false
    bootstrap_peers: []
    listen_addr: ""
  store:
    path: "./data"

geth:
  node_url: "http://YOUR_GCP_INSTANCE_IP:8545"  # Replace with your GCP instance IP
  ws_url: "ws://YOUR_GCP_INSTANCE_IP:8546"      # Replace with your GCP instance IP  
  api_key: ""                                   # No API key needed for your own Geth node

indexer:
  block_polling_interval: 12.0
  batch_size: 100
  start_height: 1800000  # Adjust based on your needs
  pipeline:
    fetch_blocks:
      workers: 6          # Increased for better performance with dedicated node
      buffer_size: 150
    process_transactions:
      workers: 10         # More workers since we have full transaction type support
      buffer_size: 300
    process_logs:
      workers: 6
      buffer_size: 150

logger:
  level: "info"
  development: false

# GCP-specific settings (optional)
monitoring:
  enabled: true
  metrics_port: 9090
  
# Connection settings optimized for GCP
network:
  timeout: 30s
  retry_attempts: 5
  retry_delay: 2s
