defradb:
  host: "localhost"
  port: 9181
  keyring_secret: ""
  p2p:
    enabled: false
    bootstrap_peers: []
    listen_addr: ""
  store:
    path: "./data"

alchemy:
  api_key: "${ALCHEMY_API_KEY}" # Add your Alchemy API key here
  network: "${NETWORK_NAME}"

indexer:
  block_polling_interval: 12.0
  batch_size: 100
  start_height: 1800000
  pipeline:
    fetch_blocks:
      workers: 4
      buffer_size: 100
    process_transactions:
      workers: 4
      buffer_size: 100
    store_data:
      workers: 4
      buffer_size: 100
