name: event
steps:
  - name: filter_raw_fields
    type: filter
    config:
      fields:
        - name
        - logIndex
        - params

  - name: normalize_fields
    type: normalize
    config:
      fields:
        - name
      case: lower

  - name: map_fields
    type: enrich
    config:
      fields:
        name: "name"
        logIndex: "logIndex"
        params: "params"

  - name: validate_event
    type: validate
    config:
      required:
        - name
        - logIndex
        - params

  - name: store_event
    type: enrich
    config:
      mutation: |
        mutation {
          create_Event(input: {
            name: $name
            logIndex: $logIndex
            params: $params
          }) {
            _docID
            name
          }
        }