name: event
steps:
  - name: filter_raw_fields
    type: filter
    config:
      fields:
        - name
        - logIndex
        - params
        - log_id

  - name: normalize_fields
    type: normalize
    config:
      fields:
        - name
      case: lower

  - name: map_fields
    type: enrich
    config:
      fields:
        name: "name"
        logIndex: "logIndex"
        params: "params"
        log_id: "log_id"

  - name: validate_event
    type: validate
    config:
      required:
        - name
        - logIndex
        - params
        - log_id

  - name: store_event
    type: enrich
    config:
      query: |
        mutation CreateEvent {
          create_Event(input: {
            name: $name
            params: $params
            log_id: $log_id
          }) {
            _docID
            name
          }
        }