name: log
steps:
  - name: filter_raw_fields
    type: filter
    config:
      fields:
        - address
        - topics
        - data
        - blockNumber
        - transactionHash
        - transactionIndex
        - blockHash
        - logIndex
        - removed

  - name: normalize_addresses
    type: normalize
    config:
      fields:
        - address
        - topics[*]
        - blockHash
        - transactionHash
      case: lower

  - name: normalize_numbers
    type: normalize
    config:
      fields:
        - blockNumber
        - transactionIndex
        - logIndex
      format: string

  - name: decode_topics
    type: enrich
    config:
      fields:
        eventSignature: "topics[0]"
        decoded_topics:
          - name: "topic1"
            value: "topics[1]"
            decode: "hex"
          - name: "topic2"
            value: "topics[2]"
            decode: "hex"
          - name: "topic3"
            value: "topics[3]"
            decode: "hex"

  - name: map_fields
    type: enrich
    config:
      fields:
        address: "address"
        topics: "topics"
        data: "data"
        blockNumber: "blockNumber"
        transactionHash: "transactionHash"
        transactionIndex: "transactionIndex"
        blockHash: "blockHash"
        logIndex: "logIndex"
        removed: "removed"

  - name: validate_log
    type: validate
    config:
      rules:
        - field: address
          required: true
          format: "^0x[a-f0-9]{40}$"
        - field: topics
          required: true
          type: array
        - field: data
          required: true
        - field: logIndex
          required: true
          type: number
        - field: transactionHash
          required: true
          format: "^0x[a-f0-9]{64}$"
        - field: blockHash
          required: true
          format: "^0x[a-f0-9]{64}$"
        - field: blockNumber
          required: true
          type: number
        - field: transactionIndex
          required: true
          type: number

  - name: store_log
    type: enrich
    config:
      mutation: |
        mutation {
          create_Log(input: {
            address: $address
            topics: $topics
            data: $data
            blockNumber: $blockNumber
            transactionHash: $transactionHash
            transactionIndex: $transactionIndex
            blockHash: $blockHash
            logIndex: $logIndex
            removed: $removed
          }) {
            _docID
            address
            transactionHash
          }
        }
