name: transaction
steps:
  - name: filter_raw_fields
    type: filter
    config:
      fields:
        - hash
        - blockHash
        - blockNumber
        - from
        - to
        - gas
        - gasPrice
        - input
        - nonce
        - value
        - type
        - chainId
        - v
        - r
        - s
        - logs

  - name: normalize_addresses
    type: normalize
    config:
      fields:
        - hash
        - blockHash
        - from
        - to
      case: lower

  - name: normalize_numbers
    type: normalize
    config:
      fields:
        - blockNumber
        - gas
        - gasPrice
        - nonce
        - value
        - type
        - chainId
        - v
      format: string

  - name: map_fields
    type: enrich
    config:
      fields:
        hash: "hash"
        blockHash: "blockHash"
        blockNumber: "blockNumber"
        from: "from"
        to: "to"
        gas: "gas"
        gasPrice: "gasPrice"
        input: "input"
        nonce: "nonce"
        value: "value"
        type: "type"
        chainId: "chainId"
        v: "v"
        r: "r"
        s: "s"
        logs: "logs"

  - name: process_logs
    type: enrich
    config:
      arrayField: "logs"
      structure:
        required:
          - logIndex
          - transactionHash
        optional:
          - events
          - address
          - topics
          - data
          - blockNumber
          - blockHash
          - transactionIndex
          - removed
      defaults:
        events: []
        removed: false

  - name: prepare_fields
    type: enrich
    config:
      fields:
        network:
          value: "${env.NETWORK_NAME}"
        indexedAt:
          value: "${now()}"
        accessList:
          value: ""
        yParity:
          value: ""
        maxFeePerGas:
          value: ""
        maxPriorityFeePerGas:
          value: ""
        status:
          value: true

  - name: validate_transaction
    type: validate
    config:
      required:
        - hash
        - blockHash
        - blockNumber
        - from
        - gas
        - gasPrice
        - input
        - nonce
        - value
        - type
        - chainId
        - v
        - r
        - s

  - name: store_transaction
    type: enrich
    config:
      mutation: |
        mutation {
          create_Transaction(input: {
            hash: $hash
            blockHash: $blockHash
            blockNumber: $blockNumber
            from: $from
            to: $to
            gas: $gas
            gasPrice: $gasPrice
            input: $input
            nonce: $nonce
            value: $value
            type: $type
            chainId: $chainId
            v: $v
            r: $r
            s: $s
            network: $network
            indexedAt: $indexedAt
            yParity: $yParity
            maxFeePerGas: $maxFeePerGas
            maxPriorityFeePerGas: $maxPriorityFeePerGas
            accessList: $accessList
            status: $status
            logs: $logs
          }) {
            _docID
            hash
            blockHash
          }
        }
