name: transaction
steps:
  - name: filter_raw_fields
    type: filter
    config:
      fields:
        - hash
        - blockHash
        - blockNumber
        - from
        - to
        - gas
        - gasPrice
        - input
        - nonce
        - value
        - type
        - chainId
        - v
        - r
        - s
        - block_id
        - transactionIndex
        - yParity
        - maxFeePerGas
        - maxPriorityFeePerGas
        - accessList
        - indexedAt
        - network
        - status

  - name: normalize_addresses
    type: normalize
    config:
      fields:
        - hash
        - blockHash
        - from
        - to
      case: lower

  - name: normalize_value
    type: normalize
    config:
      fields:
        - value
      format: string
      transform: |
        function transform(value) {
          if (!value) return "0";
          if (typeof value === "string") return value;
          if (typeof value === "object") {
            if (value.value) {
              return value.value.toString();
            }
            if (value.hex) {
              return value.hex;
            }
            return JSON.stringify(value);
          }
          return value.toString();
        }

  - name: normalize_numbers
    type: normalize
    config:
      fields:
        - blockNumber
        - gas
        - gasPrice
        - nonce
        - type
        - chainId
        - v
        - maxFeePerGas
        - maxPriorityFeePerGas
      format: string

  - name: map_fields
    type: enrich
    config:
      fields:
        hash: "hash"
        block_id: "block_id"  # This will be set to the block's DocID in the indexer
        from: "from"
        to: "to"
        value: "value"
        gas: "gas"
        gasPrice: "gasPrice"
        input: "input"
        nonce: "nonce"
        index: "transactionIndex"
        status: "status"

  - name: validate_fields
    type: validate
    config:
      required:
        - hash
        - block_id
        - from
        - to
        - value
        - gas
        - gasPrice
        - input
        - nonce
        - index
        - status

  - name: prepare_fields
    type: enrich
    config:
      fields:
        network:
          value: "${env.NETWORK_NAME}"
        indexedAt:
          value: "${now()}"
        accessList:
          value: ""
        yParity:
          value: ""
        maxFeePerGas:
          value: ""
        maxPriorityFeePerGas:
          value: ""
        status:
          value: true

  - name: store_transaction
    type: enrich
    config:
      query: |
        mutation CreateTransaction(
          $hash: String!,
          $block_id: ID!,
          $from: String!,
          $to: String!,
          $value: String!,
          $gas: String!,
          $gasPrice: String!,
          $input: String!,
          $nonce: String!,
          $index: String!,
          $status: Boolean!
        ) {
          create_Transaction(input: [{
            hash: $hash
            block_id: $block_id
            from: $from
            to: $to
            value: $value
            gas: $gas
            gasPrice: $gasPrice
            input: $input
            nonce: $nonce
            index: $index
            status: $status
          }]) {
            _docID
            hash
          }
        }
