defradb:
  url: "http://localhost:9181"
  keyring_secret: "test_secret"
  p2p:
    enabled: false
    bootstrap_peers: []
    listen_addr: ""
  store:
    path: "./test_data"

geth:
  node_url: "${GCP_GETH_NODE_URL}"
  ws_url: "${GCP_GETH_WS_URL}"
  api_key: "${GCP_GETH_API_KEY}"

indexer:
  block_polling_interval: 12.0
  batch_size: 10
  start_height: 1800000
  pipeline:
    fetch_blocks:
      workers: 2
      buffer_size: 50
    process_transactions:
      workers: 4
      buffer_size: 100
    store_data:
      workers: 2
      buffer_size: 50

logger:
  development: true
